name: deploy to test

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - run: npm install && npm run build
        env:
          ASSET_PREFIX: '/prod/myapp'
          NEXT_PUBLIC_BASE_URL: 'https://staging.hitomoshi.org/prod/myapp/'

      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: rsync deploy
        run: |
          ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022 chrc384105@sv16470.xserver.jp 'rm -rf /home/chrc384105/hitomoshi.org/public_html/prod/myapp/*'
          rsync -auzrv --delete --exclude .htaccess -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" ./out/* chrc384105@sv16470.xserver.jp:/home/chrc384105/hitomoshi.org/public_html/prod/myapp/ --exclude .htaccess
